// パラメータ設定 (CONFIG)
// このファイルはエディターツールによって自動更新されます
let CONFIG = {
    "payouts": {
        "BIG": 300,
        "REG": 90,
        "STAR": 8,
        "WATERMELON": 6,
        "CHERRY": 4,
        "REPLAY": 3
    },
    "timings": {
        "reel1": 1400,
        "reel2": 150,
        "reel3": 150,
        "next": 400,
        "nextWin": 800
    },
    "probabilities": {
        "1": {
            "HAZE": 54594,
            "BB_A": 250,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 800,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "2": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "3": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "4": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "5": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "6": {
            "HAZE": 53984,
            "BB_A": 300,
            "BB_B": 120,
            "BB_C": 120,
            "BB_D": 8,
            "RB_A": 150,
            "RB_B": 150,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        }
    },
    "reelStrips": [
        [
            "WATERMELON",
            "CHERRY",
            "STAR",
            "WATERMELON",
            "RED7",
            "REPLAY",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "STAR",
            "BLUE7",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "CHERRY",
            "REPLAY",
            "STAR",
            "BAR",
            "WATERMELON",
            "REPLAY"
        ],
        [
            "BLANK",
            "REPLAY",
            "STAR",
            "WATERMELON",
            "RED7",
            "CHERRY",
            "REPLAY",
            "STAR",
            "WATERMELON",
            "BAR",
            "CHERRY",
            "REPLAY",
            "STAR",
            "STAR",
            "BLUE7",
            "BLANK",
            "REPLAY",
            "STAR",
            "STAR",
            "CHERRY"
        ],
        [
            "WATERMELON",
            "STAR",
            "REPLAY",
            "CHERRY",
            "RED7",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "STAR",
            "BAR",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "BLANK",
            "CHERRY",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "BLUE7",
            "CHERRY"
        ]
    ]
};
