// パラメータ設定 (CONFIG)
// このファイルはエディターツールによって自動更新されます
let CONFIG = {
    "payouts": {
        "BIG": 300,
        "REG": 90,
        "STAR": 8,
        "WATERMELON": 6,
        "CHERRY": 4,
        "REPLAY": 3
    },
    "timings": {
        "reel1": 1400,
        "reel2": 150,
        "reel3": 150,
        "next": 400,
        "nextWin": 800
    },
    "probabilities": {
        "1": {
            "HAZE": 8224,
            "BB_A": 10,
            "BB_B": 10,
            "BB_C": 10,
            "BB_D": 10,
            "RB_A": 10,
            "RB_B": 10,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "2": {
            "HAZE": 8169,
            "BB_A": 10,
            "BB_B": 10,
            "BB_C": 10,
            "BB_D": 10,
            "RB_A": 15,
            "RB_B": 10,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 900,
            "BELL_B": 450,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "3": {
            "HAZE": 6854,
            "BB_A": 15,
            "BB_B": 15,
            "BB_C": 15,
            "BB_D": 15,
            "RB_A": 20,
            "RB_B": 20,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 500,
            "BELL_C": 500,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "4": {
            "HAZE": 6814,
            "BB_A": 20,
            "BB_B": 20,
            "BB_C": 20,
            "BB_D": 20,
            "RB_A": 25,
            "RB_B": 25,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 500,
            "BELL_C": 500,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "5": {
            "HAZE": 6774,
            "BB_A": 25,
            "BB_B": 25,
            "BB_C": 25,
            "BB_D": 25,
            "RB_A": 30,
            "RB_B": 30,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 500,
            "BELL_C": 500,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "6": {
            "HAZE": 7694,
            "BB_A": 30,
            "BB_B": 30,
            "BB_C": 30,
            "BB_D": 30,
            "RB_A": 35,
            "RB_B": 35,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 500,
            "BELL_C": 500,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        }
    },
    "reelStrips": [
        [
            "WATERMELON",
            "CHERRY",
            "STAR",
            "WATERMELON",
            "RED7",
            "REPLAY",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "STAR",
            "BLUE7",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "CHERRY",
            "REPLAY",
            "STAR",
            "BAR",
            "WATERMELON",
            "REPLAY"
        ],
        [
            "BLANK",
            "REPLAY",
            "STAR",
            "WATERMELON",
            "RED7",
            "CHERRY",
            "REPLAY",
            "STAR",
            "WATERMELON",
            "BAR",
            "CHERRY",
            "REPLAY",
            "STAR",
            "STAR",
            "BLUE7",
            "BLANK",
            "REPLAY",
            "STAR",
            "STAR",
            "CHERRY"
        ],
        [
            "WATERMELON",
            "STAR",
            "REPLAY",
            "CHERRY",
            "RED7",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "STAR",
            "BAR",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "BLANK",
            "CHERRY",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "BLUE7",
            "CHERRY"
        ]
    ]
};
