// パラメータ設定 (CONFIG)
// このファイルはエディターツールによって自動更新されます
let CONFIG = {
    "reelLayout": {
        "translateY": -38,
        "scale": 1.41
    },
    "payouts": {
        "BIG": 300,
        "REG": 90,
        "STAR": 8,
        "WATERMELON": 6,
        "CHERRY": 4,
        "REPLAY": 3
    },
    "timings": {
        "reel1": 1406,
        "reel2": 156,
        "reel3": 156,
        "next": 782,
        "nextWin": 800
    },
    "probabilities_A": {
        "1": {
            "HAZE": 54594,
            "BB_A": 250,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 800,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "2": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "3": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "4": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "5": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "6": {
            "HAZE": 37184,
            "BB_A": 500,
            "BB_B": 120,
            "BB_C": 120,
            "BB_D": 8,
            "RB_A": 150,
            "RB_B": 150,
            "REPLAY_A": 5000,
            "REPLAY_B": 4000,
            "REPLAY_C": 1000,
            "BELL_A": 7000,
            "BELL_B": 6000,
            "BELL_C": 400,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        }
    },
    "probabilities_BB": {
        "1": {
            "HAZE": 8632,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 16000,
            "BELL_B": 16000,
            "BELL_C": 16000,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "2": {
            "HAZE": 8632,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 16000,
            "BELL_B": 16000,
            "BELL_C": 16000,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "3": {
            "HAZE": 8632,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 16000,
            "BELL_B": 16000,
            "BELL_C": 16000,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "4": {
            "HAZE": 8632,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 16000,
            "BELL_B": 16000,
            "BELL_C": 16000,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "5": {
            "HAZE": 8632,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 16000,
            "BELL_B": 16000,
            "BELL_C": 16000,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "6": {
            "HAZE": 8632,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 16000,
            "BELL_B": 16000,
            "BELL_C": 16000,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        }
    },
    "probabilities_RB": {
        "1": {
            "HAZE": 13068,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 1000,
            "REPLAY_B": 1000,
            "REPLAY_C": 1000,
            "BELL_A": 8000,
            "BELL_B": 8000,
            "BELL_C": 8000,
            "CHERRY_A": 200,
            "CHERRY_B": 0,
            "CHERRY_C": 0,
            "SUICA_A": 200,
            "SUICA_B": 0,
            "SUICA_C": 0,
            "CHANCE_A": 25068,
            "CHANCE_B": 0,
            "CHANCE_C": 0
        },
        "2": {
            "HAZE": 13068,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 1000,
            "REPLAY_B": 1000,
            "REPLAY_C": 1000,
            "BELL_A": 8000,
            "BELL_B": 8000,
            "BELL_C": 8000,
            "CHERRY_A": 200,
            "CHERRY_B": 0,
            "CHERRY_C": 0,
            "SUICA_A": 200,
            "SUICA_B": 0,
            "SUICA_C": 0,
            "CHANCE_A": 25068,
            "CHANCE_B": 0,
            "CHANCE_C": 0
        },
        "3": {
            "HAZE": 13068,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 1000,
            "REPLAY_B": 1000,
            "REPLAY_C": 1000,
            "BELL_A": 8000,
            "BELL_B": 8000,
            "BELL_C": 8000,
            "CHERRY_A": 200,
            "CHERRY_B": 0,
            "CHERRY_C": 0,
            "SUICA_A": 200,
            "SUICA_B": 0,
            "SUICA_C": 0,
            "CHANCE_A": 25068,
            "CHANCE_B": 0,
            "CHANCE_C": 0
        },
        "4": {
            "HAZE": 13068,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 1000,
            "REPLAY_B": 1000,
            "REPLAY_C": 1000,
            "BELL_A": 8000,
            "BELL_B": 8000,
            "BELL_C": 8000,
            "CHERRY_A": 200,
            "CHERRY_B": 0,
            "CHERRY_C": 0,
            "SUICA_A": 200,
            "SUICA_B": 0,
            "SUICA_C": 0,
            "CHANCE_A": 25068,
            "CHANCE_B": 0,
            "CHANCE_C": 0
        },
        "5": {
            "HAZE": 25068,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 1000,
            "REPLAY_B": 0,
            "REPLAY_C": 0,
            "BELL_A": 14000,
            "BELL_B": 0,
            "BELL_C": 0,
            "CHERRY_A": 200,
            "CHERRY_B": 0,
            "CHERRY_C": 0,
            "SUICA_A": 200,
            "SUICA_B": 0,
            "SUICA_C": 0,
            "CHANCE_A": 25068,
            "CHANCE_B": 0,
            "CHANCE_C": 0
        },
        "6": {
            "HAZE": 25068,
            "BB_A": 0,
            "BB_B": 0,
            "BB_C": 0,
            "BB_D": 0,
            "RB_A": 0,
            "RB_B": 0,
            "REPLAY_A": 1000,
            "REPLAY_B": 0,
            "REPLAY_C": 0,
            "BELL_A": 14000,
            "BELL_B": 0,
            "BELL_C": 0,
            "CHERRY_A": 200,
            "CHERRY_B": 0,
            "CHERRY_C": 0,
            "SUICA_A": 200,
            "SUICA_B": 0,
            "SUICA_C": 0,
            "CHANCE_A": 25068,
            "CHANCE_B": 0,
            "CHANCE_C": 0
        }
    },
    "reelStrips": [
        [
            "WATERMELON",
            "CHERRY",
            "STAR",
            "WATERMELON",
            "RED7",
            "REPLAY",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "STAR",
            "BLUE7",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "CHERRY",
            "REPLAY",
            "STAR",
            "BAR",
            "WATERMELON",
            "REPLAY"
        ],
        [
            "BLANK",
            "REPLAY",
            "STAR",
            "WATERMELON",
            "RED7",
            "CHERRY",
            "REPLAY",
            "STAR",
            "WATERMELON",
            "BAR",
            "CHERRY",
            "REPLAY",
            "STAR",
            "STAR",
            "BLUE7",
            "BLANK",
            "REPLAY",
            "STAR",
            "STAR",
            "CHERRY"
        ],
        [
            "WATERMELON",
            "STAR",
            "REPLAY",
            "CHERRY",
            "RED7",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "STAR",
            "BAR",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "BLANK",
            "CHERRY",
            "WATERMELON",
            "STAR",
            "REPLAY",
            "BLUE7",
            "CHERRY"
        ]
    ],
    "payouts_BB": {
        "BIG": 200,
        "REG": 90,
        "STAR": 15,
        "WATERMELON": 6,
        "CHERRY": 4,
        "REPLAY": 3
    },
    "payouts_RB": {
        "BIG": 300,
        "REG": 90,
        "STAR": 15,
        "WATERMELON": 6,
        "CHERRY": 4,
        "REPLAY": 3
    },
    "probabilities_B": {
        "1": {
            "HAZE": 54594,
            "BB_A": 250,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 800,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "2": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "3": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "4": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "5": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "6": {
            "HAZE": 53984,
            "BB_A": 300,
            "BB_B": 120,
            "BB_C": 120,
            "BB_D": 8,
            "RB_A": 150,
            "RB_B": 150,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        }
    },
    "probabilities_C": {
        "1": {
            "HAZE": 54594,
            "BB_A": 250,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 800,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "2": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "3": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "4": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "5": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "6": {
            "HAZE": 53984,
            "BB_A": 300,
            "BB_B": 120,
            "BB_C": 120,
            "BB_D": 8,
            "RB_A": 150,
            "RB_B": 150,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        }
    },
    "probabilities_D": {
        "1": {
            "HAZE": 54594,
            "BB_A": 250,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 800,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        },
        "2": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "3": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "4": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "5": {
            "HAZE": 56768,
            "BB_A": 280,
            "BB_B": 80,
            "BB_C": 100,
            "BB_D": 8,
            "RB_A": 100,
            "RB_B": 100,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 800,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 400,
            "CHERRY_B": 200,
            "CHERRY_C": 200,
            "SUICA_A": 200,
            "SUICA_B": 200,
            "SUICA_C": 100,
            "CHANCE_A": 100,
            "CHANCE_B": 50,
            "CHANCE_C": 50
        },
        "6": {
            "HAZE": 53984,
            "BB_A": 300,
            "BB_B": 120,
            "BB_C": 120,
            "BB_D": 8,
            "RB_A": 150,
            "RB_B": 150,
            "REPLAY_A": 2000,
            "REPLAY_B": 2000,
            "REPLAY_C": 1000,
            "BELL_A": 1000,
            "BELL_B": 400,
            "BELL_C": 400,
            "CHERRY_A": 1000,
            "CHERRY_B": 100,
            "CHERRY_C": 4,
            "SUICA_A": 1000,
            "SUICA_B": 1000,
            "SUICA_C": 200,
            "CHANCE_A": 200,
            "CHANCE_B": 200,
            "CHANCE_C": 200
        }
    },
    "ceilings": {
        "A": 666,
        "B": 444,
        "C": 333,
        "D": 100
    },
    "modeTransitions": {
        "initial": {
            "1": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "2": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "3": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "4": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "5": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "6": {
                "A": 20,
                "B": 10,
                "C": 30,
                "D": 40
            }
        },
        "bonus": {
            "1": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "2": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "3": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "4": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "5": {
                "A": 25,
                "B": 25,
                "C": 25,
                "D": 25
            },
            "6": {
                "A": 22,
                "B": 25,
                "C": 26,
                "D": 27
            }
        }
    }
};
